# Generated by Django 4.1.1 on 2022-09-30 13:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(4)])),
                ('genre', models.CharField(max_length=256)),
                ('time_added', models.DateTimeField()),
                ('file', models.FileField(upload_to='music/media/audio', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav'])])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
