# Generated by Django 4.1.1 on 2022-09-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='music/media/avatars'),
        ),
    ]
