# Generated by Django 4.1.1 on 2022-10-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_alter_user_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
